### ISSUE TITLE
Multiple Droppable

### ISSUE THREAD

**Issue by ekabolotina** [dsimushkin/react-draggable-hoc#3]
Is it possible to use multiple Droppable within same component?

**Comment by dsimushkin** [comment]
@ekabolotina 

Sorry for the late response.
Yes, of course. Just straight away usage.
I've added an [example](https://dsimushkin.github.io/react-draggable-hoc/#/demo/multiBin) of multiple bin (droppable).

You can also check the  [demo with source code](https://codesandbox.io/s/github/dsimushkin/react-draggable-hoc/tree/master/demo?file=/src/MultiBin.tsx)

Also, 2.1.0 has some bugfix on async operations calls. Please update if you didn't.

Best regards.

**Comment by dsimushkin** [comment]
@ekabolotina 

Hello, once again. I've added support for nested droppables in v2.3.0 and added an example.
When droppables are nested from DOM perspective everything is supported out of box.

When the droppables are not nested from DOM perspective, but overlap from user perspective, `priority` prop of Droppable (config attribute of useDroppable) should be used.

Notice that this is done via defaultDroppableMethod, so overriding Droppable `method` will break the current implementation.

Also, as of v2.2.0 dragProps are required on draggables.

Best regards.
